-- Changeset: 20260118-001-activemq-jdbc (author: foundryvtt)
-- Target DB: PostgreSQL

BEGIN;

CREATE TABLE ACTIVEMQ_MSGS (
  ID              bigserial      NOT NULL,
  CONTAINER       varchar(250)   NOT NULL,
  MSGID_PROD      varchar(250)   NOT NULL,
  MSGID_SEQ       bigint         NOT NULL,
  EXPIRATION      bigint,
  PRIORITY        smallint,
  MSG             bytea          NOT NULL,
  XID             varchar(250),
  KAFKA_TOPIC     text,
  KAFKA_PARTITION int,
  KAFKA_OFFSET    bigint,
  KAFKA_KEY       text,
  HEADERS         jsonb,
  STATUS          varchar(16)    NOT NULL,
  CREATED_AT      timestamptz    NOT NULL DEFAULT now(),
  UPDATED_AT      timestamptz    NOT NULL DEFAULT now(),
  CONSUMED_AT     timestamptz,
  ATTEMPT_COUNT   int            NOT NULL DEFAULT 0,
  LAST_ERROR      text,
  NEXT_RETRY_AT   timestamptz,
  IDEMPOTENCY_KEY text,
  CONSTRAINT ACTIVEMQ_MSGS_PKEY PRIMARY KEY (ID)
);

ALTER TABLE ACTIVEMQ_MSGS
  ADD CONSTRAINT UX_ACTIVEMQ_MSGS_MSGID
  UNIQUE (CONTAINER, MSGID_PROD, MSGID_SEQ);

ALTER TABLE ACTIVEMQ_MSGS
  ADD CONSTRAINT ACTIVEMQ_MSGS_STATUS_CHK
  CHECK (STATUS IN ('PENDING','RUNNING','DONE','FAILED'));

CREATE INDEX IDX_ACTIVEMQ_MSGS_STATUS_RETRY
  ON ACTIVEMQ_MSGS (STATUS, NEXT_RETRY_AT, ID);

CREATE INDEX IDX_ACTIVEMQ_MSGS_KAFKA_OFFSET
  ON ACTIVEMQ_MSGS (KAFKA_TOPIC, KAFKA_PARTITION, KAFKA_OFFSET);

ALTER TABLE ACTIVEMQ_MSGS
  ADD CONSTRAINT UX_ACTIVEMQ_MSGS_IDEMPOTENCY
  UNIQUE (IDEMPOTENCY_KEY);

CREATE TABLE ACTIVEMQ_ACKS (
  CONTAINER        varchar(250) NOT NULL,
  CLIENT_ID        varchar(250),
  SUB_NAME         varchar(250),
  CONSUMER_GROUP   varchar(250) NOT NULL,
  KAFKA_TOPIC      text         NOT NULL,
  KAFKA_PARTITION  int          NOT NULL,
  COMMITTED_OFFSET bigint,
  LAST_MSG_ID      bigint,
  UPDATED_AT       timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT ACTIVEMQ_ACKS_PKEY
    PRIMARY KEY (CONTAINER, CONSUMER_GROUP, KAFKA_TOPIC, KAFKA_PARTITION)
);

ALTER TABLE ACTIVEMQ_ACKS
  ADD CONSTRAINT FK_ACTIVEMQ_ACKS_LAST_MSG_ID
  FOREIGN KEY (LAST_MSG_ID)
  REFERENCES ACTIVEMQ_MSGS (ID)
  ON DELETE SET NULL;

CREATE INDEX IDX_ACTIVEMQ_ACKS_LAST_MSG_ID
  ON ACTIVEMQ_ACKS (LAST_MSG_ID);

CREATE TABLE ACTIVEMQ_LOCK (
  LOCK_KEY     varchar(250) NOT NULL,
  OWNER_ID     varchar(250) NOT NULL,
  LOCKED_UNTIL timestamptz  NOT NULL,
  CONSTRAINT ACTIVEMQ_LOCK_PKEY PRIMARY KEY (LOCK_KEY)
);

CREATE INDEX IDX_ACTIVEMQ_LOCK_UNTIL
  ON ACTIVEMQ_LOCK (LOCKED_UNTIL);

COMMIT;
