/*
 * Foundry REST API Documentation ### How to use Foundry REST API: - Install the [Foundry VTT
 * Module](https://github.com/ThreeHats/foundryvtt-rest-api) - Get an API key for the public relay
 * server at
 * [https://foundryvtt-rest-api-relay.fly.dev/](https://foundryvtt-rest-api-relay.fly.dev/) -
 * Download [Postman](https://www.postman.com/downloads/) and the import the API Test Collection for
 * an easy way to start testing endpoints. - Read this documentation for information about how to
 * use each endpoint --- Foundry REST API provides various API endpoints for fetching and
 * interacting with your foundry world data through a node.js server that act as a relay. ##
 * **Getting started guide** To start using the Foundry REST API, you need to - - Have your API key
 * in the module settings. - Each request must have the your API key in the \"x-api-key\" header. -
 * Endpoints other than /clients require a clientId parameter that matches a connected world.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */

package com.foundryvtt.bot.spirit.openapi.relay.v13.system.dnd5e.model;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.foundryvtt.bot.spirit.openapi.relay.v13.system.dnd5e.invoker.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Request payload for roll execution.
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
@JsonIgnoreProperties(ignoreUnknown = true)
public class RollRequest {
    public static final String SERIALIZED_NAME_FORMULA = "formula";
    @SerializedName(SERIALIZED_NAME_FORMULA)
    @JsonProperty(SERIALIZED_NAME_FORMULA)
    @jakarta.annotation.Nonnull
    private String formula;

    public static final String SERIALIZED_NAME_ITEM_UUID = "itemUuid";
    @SerializedName(SERIALIZED_NAME_ITEM_UUID)
    @JsonProperty(SERIALIZED_NAME_ITEM_UUID)
    @jakarta.annotation.Nullable private String itemUuid;

    public static final String SERIALIZED_NAME_FLAVOR = "flavor";
    @SerializedName(SERIALIZED_NAME_FLAVOR)
    @JsonProperty(SERIALIZED_NAME_FLAVOR)
    @jakarta.annotation.Nullable private String flavor;

    public static final String SERIALIZED_NAME_CREATE_CHAT_MESSAGE = "createChatMessage";
    @SerializedName(SERIALIZED_NAME_CREATE_CHAT_MESSAGE)
    @JsonProperty(SERIALIZED_NAME_CREATE_CHAT_MESSAGE)
    @jakarta.annotation.Nullable private Boolean createChatMessage = true;

    public static final String SERIALIZED_NAME_TARGET = "target";
    @SerializedName(SERIALIZED_NAME_TARGET)
    @JsonProperty(SERIALIZED_NAME_TARGET)
    @jakarta.annotation.Nullable private String target;

    public static final String SERIALIZED_NAME_SPEAKER = "speaker";
    @SerializedName(SERIALIZED_NAME_SPEAKER)
    @JsonProperty(SERIALIZED_NAME_SPEAKER)
    @jakarta.annotation.Nullable private String speaker;

    public static final String SERIALIZED_NAME_WHISPER = "whisper";
    @SerializedName(SERIALIZED_NAME_WHISPER)
    @JsonProperty(SERIALIZED_NAME_WHISPER)
    @jakarta.annotation.Nullable private List<String> whisper = new ArrayList<>();

    public RollRequest() {
    }

    public RollRequest formula(@jakarta.annotation.Nonnull String formula) {
        this.formula = formula;
        return this;
    }

    /**
     * Dice formula to execute.
     * 
     * @return formula
     */
    @jakarta.annotation.Nonnull
    public String getFormula() {
        return formula;
    }

    public void setFormula(@jakarta.annotation.Nonnull String formula) {
        this.formula = formula;
    }

    public RollRequest itemUuid(@jakarta.annotation.Nullable String itemUuid) {
        this.itemUuid = itemUuid;
        return this;
    }

    /**
     * Get itemUuid
     * 
     * @return itemUuid
     */
    @jakarta.annotation.Nullable public String getItemUuid() {
        return itemUuid;
    }

    public void setItemUuid(@jakarta.annotation.Nullable String itemUuid) {
        this.itemUuid = itemUuid;
    }

    public RollRequest flavor(@jakarta.annotation.Nullable String flavor) {
        this.flavor = flavor;
        return this;
    }

    /**
     * Get flavor
     * 
     * @return flavor
     */
    @jakarta.annotation.Nullable public String getFlavor() {
        return flavor;
    }

    public void setFlavor(@jakarta.annotation.Nullable String flavor) {
        this.flavor = flavor;
    }

    public RollRequest createChatMessage(@jakarta.annotation.Nullable Boolean createChatMessage) {
        this.createChatMessage = createChatMessage;
        return this;
    }

    /**
     * Get createChatMessage
     * 
     * @return createChatMessage
     */
    @jakarta.annotation.Nullable public Boolean getCreateChatMessage() {
        return createChatMessage;
    }

    public void setCreateChatMessage(@jakarta.annotation.Nullable Boolean createChatMessage) {
        this.createChatMessage = createChatMessage;
    }

    public RollRequest target(@jakarta.annotation.Nullable String target) {
        this.target = target;
        return this;
    }

    /**
     * Get target
     * 
     * @return target
     */
    @jakarta.annotation.Nullable public String getTarget() {
        return target;
    }

    public void setTarget(@jakarta.annotation.Nullable String target) {
        this.target = target;
    }

    public RollRequest speaker(@jakarta.annotation.Nullable String speaker) {
        this.speaker = speaker;
        return this;
    }

    /**
     * Get speaker
     * 
     * @return speaker
     */
    @jakarta.annotation.Nullable public String getSpeaker() {
        return speaker;
    }

    public void setSpeaker(@jakarta.annotation.Nullable String speaker) {
        this.speaker = speaker;
    }

    public RollRequest whisper(@jakarta.annotation.Nullable List<String> whisper) {
        this.whisper = whisper;
        return this;
    }

    public RollRequest addWhisperItem(String whisperItem) {
        if (this.whisper == null) {
            this.whisper = new ArrayList<>();
        }
        this.whisper.add(whisperItem);
        return this;
    }

    /**
     * Get whisper
     * 
     * @return whisper
     */
    @jakarta.annotation.Nullable public List<String> getWhisper() {
        return whisper;
    }

    public void setWhisper(@jakarta.annotation.Nullable List<String> whisper) {
        this.whisper = whisper;
    }

    /**
     * A container for additional, undeclared properties. This is a holder for any undeclared
     * properties as specified with the 'additionalProperties' keyword in the OAS document.
     */
    private Map<String, Object> additionalProperties;

    /**
     * Set the additional (undeclared) property with the specified name and value. If the property
     * does not already exist, create it otherwise replace it.
     *
     * @param key   name of the property
     * @param value value of the property
     * @return the RollRequest instance itself
     */
    public RollRequest putAdditionalProperty(String key, Object value) {
        if (this.additionalProperties == null) {
            this.additionalProperties = new HashMap<String, Object>();
        }
        this.additionalProperties.put(key, value);
        return this;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String key, Object value) {
        putAdditionalProperty(key, value);
    }

    /**
     * Return the additional (undeclared) property.
     *
     * @return a map of objects
     */
    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return additionalProperties;
    }

    /**
     * Return the additional (undeclared) property with the specified name.
     *
     * @param key name of the property
     * @return an object
     */
    public Object getAdditionalProperty(String key) {
        if (this.additionalProperties == null) {
            return null;
        }
        return this.additionalProperties.get(key);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RollRequest rollRequest = (RollRequest) o;
        return Objects.equals(this.formula, rollRequest.formula) &&
                Objects.equals(this.itemUuid, rollRequest.itemUuid) &&
                Objects.equals(this.flavor, rollRequest.flavor) &&
                Objects.equals(this.createChatMessage, rollRequest.createChatMessage) &&
                Objects.equals(this.target, rollRequest.target) &&
                Objects.equals(this.speaker, rollRequest.speaker) &&
                Objects.equals(this.whisper, rollRequest.whisper) &&
                Objects.equals(this.additionalProperties, rollRequest.additionalProperties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(formula, itemUuid, flavor, createChatMessage, target, speaker, whisper,
                additionalProperties);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RollRequest {\n");
        sb.append("    formula: ").append(toIndentedString(formula)).append("\n");
        sb.append("    itemUuid: ").append(toIndentedString(itemUuid)).append("\n");
        sb.append("    flavor: ").append(toIndentedString(flavor)).append("\n");
        sb.append("    createChatMessage: ").append(toIndentedString(createChatMessage))
                .append("\n");
        sb.append("    target: ").append(toIndentedString(target)).append("\n");
        sb.append("    speaker: ").append(toIndentedString(speaker)).append("\n");
        sb.append("    whisper: ").append(toIndentedString(whisper)).append("\n");
        sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties))
                .append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces (except the first
     * line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>(Arrays.asList("formula", "itemUuid", "flavor",
                "createChatMessage", "target", "speaker", "whisper"));

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>(Arrays.asList("formula"));
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to RollRequest
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!RollRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON
                                                                // element is null
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                        "The required field(s) %s in RollRequest is not found in the empty JSON string",
                        RollRequest.openapiRequiredFields.toString()));
            }
        }

        // check to make sure all required properties/fields are present in the JSON string
        for (String requiredField : RollRequest.openapiRequiredFields) {
            if (jsonElement.getAsJsonObject().get(requiredField) == null) {
                throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                        "The required field `%s` is not found in the JSON string: %s",
                        requiredField, jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (!jsonObj.get("formula").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "Expected the field `formula` to be a primitive type in the JSON string but got `%s`",
                    jsonObj.get("formula").toString()));
        }
        if ((jsonObj.get("itemUuid") != null && !jsonObj.get("itemUuid").isJsonNull())
                && !jsonObj.get("itemUuid").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "Expected the field `itemUuid` to be a primitive type in the JSON string but got `%s`",
                    jsonObj.get("itemUuid").toString()));
        }
        if ((jsonObj.get("flavor") != null && !jsonObj.get("flavor").isJsonNull())
                && !jsonObj.get("flavor").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "Expected the field `flavor` to be a primitive type in the JSON string but got `%s`",
                    jsonObj.get("flavor").toString()));
        }
        if ((jsonObj.get("target") != null && !jsonObj.get("target").isJsonNull())
                && !jsonObj.get("target").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "Expected the field `target` to be a primitive type in the JSON string but got `%s`",
                    jsonObj.get("target").toString()));
        }
        if ((jsonObj.get("speaker") != null && !jsonObj.get("speaker").isJsonNull())
                && !jsonObj.get("speaker").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "Expected the field `speaker` to be a primitive type in the JSON string but got `%s`",
                    jsonObj.get("speaker").toString()));
        }
        // ensure the optional json data is an array if present
        if (jsonObj.get("whisper") != null && !jsonObj.get("whisper").isJsonNull()
                && !jsonObj.get("whisper").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT,
                    "Expected the field `whisper` to be an array in the JSON string but got `%s`",
                    jsonObj.get("whisper").toString()));
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!RollRequest.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'RollRequest' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<RollRequest> thisAdapter = gson.getDelegateAdapter(this,
                    TypeToken.get(RollRequest.class));

            return (TypeAdapter<T>) new TypeAdapter<RollRequest>() {
                @Override
                public void write(JsonWriter out, RollRequest value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    obj.remove("additionalProperties");
                    // serialize additional properties
                    if (value.getAdditionalProperties() != null) {
                        for (Map.Entry<String, Object> entry : value.getAdditionalProperties()
                                .entrySet()) {
                            if (entry.getValue() instanceof String)
                                obj.addProperty(entry.getKey(), (String) entry.getValue());
                            else if (entry.getValue() instanceof Number)
                                obj.addProperty(entry.getKey(), (Number) entry.getValue());
                            else if (entry.getValue() instanceof Boolean)
                                obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                            else if (entry.getValue() instanceof Character)
                                obj.addProperty(entry.getKey(), (Character) entry.getValue());
                            else {
                                JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                                if (jsonElement.isJsonArray()) {
                                    obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                                } else {
                                    obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                                }
                            }
                        }
                    }
                    elementAdapter.write(out, obj);
                }

                @Override
                public RollRequest read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    JsonObject jsonObj = jsonElement.getAsJsonObject();
                    // store additional fields in the deserialized instance
                    RollRequest instance = thisAdapter.fromJsonTree(jsonObj);
                    for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
                        if (!openapiFields.contains(entry.getKey())) {
                            if (entry.getValue().isJsonPrimitive()) { // primitive type
                                if (entry.getValue().getAsJsonPrimitive().isString())
                                    instance.putAdditionalProperty(entry.getKey(),
                                            entry.getValue().getAsString());
                                else if (entry.getValue().getAsJsonPrimitive().isNumber())
                                    instance.putAdditionalProperty(entry.getKey(),
                                            entry.getValue().getAsNumber());
                                else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                                    instance.putAdditionalProperty(entry.getKey(),
                                            entry.getValue().getAsBoolean());
                                else
                                    throw new IllegalArgumentException(String.format(
                                            java.util.Locale.ROOT,
                                            "The field `%s` has unknown primitive type. Value: %s",
                                            entry.getKey(), entry.getValue().toString()));
                            } else if (entry.getValue().isJsonArray()) {
                                instance.putAdditionalProperty(entry.getKey(),
                                        gson.fromJson(entry.getValue(), List.class));
                            } else { // JSON object
                                instance.putAdditionalProperty(entry.getKey(),
                                        gson.fromJson(entry.getValue(), HashMap.class));
                            }
                        }
                    }
                    return instance;
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of RollRequest given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of RollRequest
     * @throws IOException if the JSON string is invalid with respect to RollRequest
     */
    public static RollRequest fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, RollRequest.class);
    }

    /**
     * Convert an instance of RollRequest to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}
