/*
 * Foundry REST API Documentation ### How to use Foundry REST API: - Install the [Foundry VTT
 * Module](https://github.com/ThreeHats/foundryvtt-rest-api) - Get an API key for the public relay
 * server at
 * [https://foundryvtt-rest-api-relay.fly.dev/](https://foundryvtt-rest-api-relay.fly.dev/) -
 * Download [Postman](https://www.postman.com/downloads/) and the import the API Test Collection for
 * an easy way to start testing endpoints. - Read this documentation for information about how to
 * use each endpoint --- Foundry REST API provides various API endpoints for fetching and
 * interacting with your foundry world data through a node.js server that act as a relay. ##
 * **Getting started guide** To start using the Foundry REST API, you need to - - Have your API key
 * in the module settings. - Each request must have the your API key in the \"x-api-key\" header. -
 * Endpoints other than /clients require a clientId parameter that matches a connected world.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */

package com.foundryvtt.bot.spirit.openapi.relay.v13.system.core.api;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.foundryvtt.bot.spirit.openapi.relay.v13.system.core.invoker.ApiCallback;
import com.foundryvtt.bot.spirit.openapi.relay.v13.system.core.invoker.ApiClient;
import com.foundryvtt.bot.spirit.openapi.relay.v13.system.core.invoker.ApiException;
import com.foundryvtt.bot.spirit.openapi.relay.v13.system.core.invoker.ApiResponse;
import com.foundryvtt.bot.spirit.openapi.relay.v13.system.core.invoker.Configuration;
import com.foundryvtt.bot.spirit.openapi.relay.v13.system.core.invoker.Pair;
import com.google.gson.reflect.TypeToken;

public class SessionApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public SessionApi() {
        this(Configuration.getDefaultApiClient());
    }

    public SessionApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for endSessionDelete
     * 
     * @param xApiKey   (optional)
     * @param sessionId The session to end (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>OK</td>
     *                        <td>* X-Powered-By - <br>
     *                        * Access-Control-Allow-Origin - <br>
     *                        * Access-Control-Allow-Methods - <br>
     *                        * Access-Control-Allow-Headers - <br>
     *                        * Access-Control-Allow-Credentials - <br>
     *                        * Content-Type - <br>
     *                        * Content-Length - <br>
     *                        * ETag - <br>
     *                        * Date - <br>
     *                        * Connection - <br>
     *                        </td>
     *                        </tr>
     *                        </table>
     */
    public okhttp3.Call endSessionDeleteCall(@jakarta.annotation.Nullable String xApiKey,
            @jakarta.annotation.Nullable String sessionId, final ApiCallback _callback)
            throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/end-session";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (sessionId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("sessionId", sessionId));
        }

        final String[] localVarAccepts = {
                "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient
                .selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xApiKey != null) {
            localVarHeaderParams.put("x-api-key", localVarApiClient.parameterToString(xApiKey));
        }

        String[] localVarAuthNames = new String[] {};
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams,
                localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams,
                localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call endSessionDeleteValidateBeforeCall(
            @jakarta.annotation.Nullable String xApiKey,
            @jakarta.annotation.Nullable String sessionId, final ApiCallback _callback)
            throws ApiException {
        return endSessionDeleteCall(xApiKey, sessionId, _callback);

    }

    /**
     * /end-session Ends a headless Foundry session.
     * 
     * @param xApiKey   (optional)
     * @param sessionId The session to end (optional)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>OK</td>
     *                        <td>* X-Powered-By - <br>
     *                        * Access-Control-Allow-Origin - <br>
     *                        * Access-Control-Allow-Methods - <br>
     *                        * Access-Control-Allow-Headers - <br>
     *                        * Access-Control-Allow-Credentials - <br>
     *                        * Content-Type - <br>
     *                        * Content-Length - <br>
     *                        * ETag - <br>
     *                        * Date - <br>
     *                        * Connection - <br>
     *                        </td>
     *                        </tr>
     *                        </table>
     */
    public Object endSessionDelete(@jakarta.annotation.Nullable String xApiKey,
            @jakarta.annotation.Nullable String sessionId) throws ApiException {
        ApiResponse<Object> localVarResp = endSessionDeleteWithHttpInfo(xApiKey, sessionId);
        return localVarResp.getData();
    }

    /**
     * /end-session Ends a headless Foundry session.
     * 
     * @param xApiKey   (optional)
     * @param sessionId The session to end (optional)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>OK</td>
     *                        <td>* X-Powered-By - <br>
     *                        * Access-Control-Allow-Origin - <br>
     *                        * Access-Control-Allow-Methods - <br>
     *                        * Access-Control-Allow-Headers - <br>
     *                        * Access-Control-Allow-Credentials - <br>
     *                        * Content-Type - <br>
     *                        * Content-Length - <br>
     *                        * ETag - <br>
     *                        * Date - <br>
     *                        * Connection - <br>
     *                        </td>
     *                        </tr>
     *                        </table>
     */
    public ApiResponse<Object> endSessionDeleteWithHttpInfo(
            @jakarta.annotation.Nullable String xApiKey,
            @jakarta.annotation.Nullable String sessionId) throws ApiException {
        okhttp3.Call localVarCall = endSessionDeleteValidateBeforeCall(xApiKey, sessionId, null);
        Type localVarReturnType = new TypeToken<Object>() {
        }.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * /end-session (asynchronously) Ends a headless Foundry session.
     * 
     * @param xApiKey   (optional)
     * @param sessionId The session to end (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body
     *                      object
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>OK</td>
     *                        <td>* X-Powered-By - <br>
     *                        * Access-Control-Allow-Origin - <br>
     *                        * Access-Control-Allow-Methods - <br>
     *                        * Access-Control-Allow-Headers - <br>
     *                        * Access-Control-Allow-Credentials - <br>
     *                        * Content-Type - <br>
     *                        * Content-Length - <br>
     *                        * ETag - <br>
     *                        * Date - <br>
     *                        * Connection - <br>
     *                        </td>
     *                        </tr>
     *                        </table>
     */
    public okhttp3.Call endSessionDeleteAsync(@jakarta.annotation.Nullable String xApiKey,
            @jakarta.annotation.Nullable String sessionId, final ApiCallback<Object> _callback)
            throws ApiException {

        okhttp3.Call localVarCall = endSessionDeleteValidateBeforeCall(xApiKey, sessionId,
                _callback);
        Type localVarReturnType = new TypeToken<Object>() {
        }.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for sessionGet
     * 
     * @param xApiKey   (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>OK</td>
     *                        <td>* X-Powered-By - <br>
     *                        * Access-Control-Allow-Origin - <br>
     *                        * Access-Control-Allow-Methods - <br>
     *                        * Access-Control-Allow-Headers - <br>
     *                        * Access-Control-Allow-Credentials - <br>
     *                        * Content-Type - <br>
     *                        * Content-Length - <br>
     *                        * ETag - <br>
     *                        * Date - <br>
     *                        * Connection - <br>
     *                        </td>
     *                        </tr>
     *                        </table>
     */
    public okhttp3.Call sessionGetCall(@jakarta.annotation.Nullable String xApiKey,
            final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/session";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
                "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient
                .selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xApiKey != null) {
            localVarHeaderParams.put("x-api-key", localVarApiClient.parameterToString(xApiKey));
        }

        String[] localVarAuthNames = new String[] {};
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams,
                localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams,
                localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call sessionGetValidateBeforeCall(@jakarta.annotation.Nullable String xApiKey,
            final ApiCallback _callback) throws ApiException {
        return sessionGetCall(xApiKey, _callback);

    }

    /**
     * /session Gets the currently active headless Foundry session.
     * 
     * @param xApiKey (optional)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>OK</td>
     *                        <td>* X-Powered-By - <br>
     *                        * Access-Control-Allow-Origin - <br>
     *                        * Access-Control-Allow-Methods - <br>
     *                        * Access-Control-Allow-Headers - <br>
     *                        * Access-Control-Allow-Credentials - <br>
     *                        * Content-Type - <br>
     *                        * Content-Length - <br>
     *                        * ETag - <br>
     *                        * Date - <br>
     *                        * Connection - <br>
     *                        </td>
     *                        </tr>
     *                        </table>
     */
    public Object sessionGet(@jakarta.annotation.Nullable String xApiKey) throws ApiException {
        ApiResponse<Object> localVarResp = sessionGetWithHttpInfo(xApiKey);
        return localVarResp.getData();
    }

    /**
     * /session Gets the currently active headless Foundry session.
     * 
     * @param xApiKey (optional)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>OK</td>
     *                        <td>* X-Powered-By - <br>
     *                        * Access-Control-Allow-Origin - <br>
     *                        * Access-Control-Allow-Methods - <br>
     *                        * Access-Control-Allow-Headers - <br>
     *                        * Access-Control-Allow-Credentials - <br>
     *                        * Content-Type - <br>
     *                        * Content-Length - <br>
     *                        * ETag - <br>
     *                        * Date - <br>
     *                        * Connection - <br>
     *                        </td>
     *                        </tr>
     *                        </table>
     */
    public ApiResponse<Object> sessionGetWithHttpInfo(@jakarta.annotation.Nullable String xApiKey)
            throws ApiException {
        okhttp3.Call localVarCall = sessionGetValidateBeforeCall(xApiKey, null);
        Type localVarReturnType = new TypeToken<Object>() {
        }.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * /session (asynchronously) Gets the currently active headless Foundry session.
     * 
     * @param xApiKey   (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body
     *                      object
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>OK</td>
     *                        <td>* X-Powered-By - <br>
     *                        * Access-Control-Allow-Origin - <br>
     *                        * Access-Control-Allow-Methods - <br>
     *                        * Access-Control-Allow-Headers - <br>
     *                        * Access-Control-Allow-Credentials - <br>
     *                        * Content-Type - <br>
     *                        * Content-Length - <br>
     *                        * ETag - <br>
     *                        * Date - <br>
     *                        * Connection - <br>
     *                        </td>
     *                        </tr>
     *                        </table>
     */
    public okhttp3.Call sessionGetAsync(@jakarta.annotation.Nullable String xApiKey,
            final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = sessionGetValidateBeforeCall(xApiKey, _callback);
        Type localVarReturnType = new TypeToken<Object>() {
        }.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for sessionHandshakePost
     * 
     * @param xApiKey     (optional)
     * @param xFoundryUrl The url to your foundry game (optional)
     * @param xUsername   The username to log in with (eg. \&quot;Gamemaster\&quot;) (optional)
     * @param xPassword   The password to log in with (optional)
     * @param xWorldName  (Optional) The name of the world as it appears in foundry if the world is
     *                    not already loaded. (optional)
     * @param requestBody (optional)
     * @param _callback   Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>OK</td>
     *                        <td>* X-Powered-By - <br>
     *                        * Access-Control-Allow-Origin - <br>
     *                        * Access-Control-Allow-Methods - <br>
     *                        * Access-Control-Allow-Headers - <br>
     *                        * Access-Control-Allow-Credentials - <br>
     *                        * Content-Type - <br>
     *                        * Content-Length - <br>
     *                        * ETag - <br>
     *                        * Date - <br>
     *                        * Connection - <br>
     *                        </td>
     *                        </tr>
     *                        </table>
     */
    public okhttp3.Call sessionHandshakePostCall(@jakarta.annotation.Nullable String xApiKey,
            @jakarta.annotation.Nullable String xFoundryUrl,
            @jakarta.annotation.Nullable String xUsername,
            @jakarta.annotation.Nullable String xPassword,
            @jakarta.annotation.Nullable String xWorldName,
            @jakarta.annotation.Nullable Map<String, Object> requestBody,
            final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = requestBody;

        // create path and map variables
        String localVarPath = "/session-handshake";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
                "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
                "application/json"
        };
        final String localVarContentType = localVarApiClient
                .selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xApiKey != null) {
            localVarHeaderParams.put("x-api-key", localVarApiClient.parameterToString(xApiKey));
        }

        if (xFoundryUrl != null) {
            localVarHeaderParams.put("x-foundry-url",
                    localVarApiClient.parameterToString(xFoundryUrl));
        }

        if (xUsername != null) {
            localVarHeaderParams.put("x-username", localVarApiClient.parameterToString(xUsername));
        }

        if (xPassword != null) {
            localVarHeaderParams.put("x-password", localVarApiClient.parameterToString(xPassword));
        }

        if (xWorldName != null) {
            localVarHeaderParams.put("x-world-name",
                    localVarApiClient.parameterToString(xWorldName));
        }

        String[] localVarAuthNames = new String[] {};
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams,
                localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams,
                localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call sessionHandshakePostValidateBeforeCall(
            @jakarta.annotation.Nullable String xApiKey,
            @jakarta.annotation.Nullable String xFoundryUrl,
            @jakarta.annotation.Nullable String xUsername,
            @jakarta.annotation.Nullable String xPassword,
            @jakarta.annotation.Nullable String xWorldName,
            @jakarta.annotation.Nullable Map<String, Object> requestBody,
            final ApiCallback _callback) throws ApiException {
        return sessionHandshakePostCall(xApiKey, xFoundryUrl, xUsername, xPassword, xWorldName,
                requestBody, _callback);

    }

    /**
     * /session-handshake Creates a temporary, one-time-use, token that can be used to create a
     * headless Foundry session.
     * 
     * @param xApiKey     (optional)
     * @param xFoundryUrl The url to your foundry game (optional)
     * @param xUsername   The username to log in with (eg. \&quot;Gamemaster\&quot;) (optional)
     * @param xPassword   The password to log in with (optional)
     * @param xWorldName  (Optional) The name of the world as it appears in foundry if the world is
     *                    not already loaded. (optional)
     * @param requestBody (optional)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>OK</td>
     *                        <td>* X-Powered-By - <br>
     *                        * Access-Control-Allow-Origin - <br>
     *                        * Access-Control-Allow-Methods - <br>
     *                        * Access-Control-Allow-Headers - <br>
     *                        * Access-Control-Allow-Credentials - <br>
     *                        * Content-Type - <br>
     *                        * Content-Length - <br>
     *                        * ETag - <br>
     *                        * Date - <br>
     *                        * Connection - <br>
     *                        </td>
     *                        </tr>
     *                        </table>
     */
    public Object sessionHandshakePost(@jakarta.annotation.Nullable String xApiKey,
            @jakarta.annotation.Nullable String xFoundryUrl,
            @jakarta.annotation.Nullable String xUsername,
            @jakarta.annotation.Nullable String xPassword,
            @jakarta.annotation.Nullable String xWorldName,
            @jakarta.annotation.Nullable Map<String, Object> requestBody) throws ApiException {
        ApiResponse<Object> localVarResp = sessionHandshakePostWithHttpInfo(xApiKey, xFoundryUrl,
                xUsername, xPassword, xWorldName, requestBody);
        return localVarResp.getData();
    }

    /**
     * /session-handshake Creates a temporary, one-time-use, token that can be used to create a
     * headless Foundry session.
     * 
     * @param xApiKey     (optional)
     * @param xFoundryUrl The url to your foundry game (optional)
     * @param xUsername   The username to log in with (eg. \&quot;Gamemaster\&quot;) (optional)
     * @param xPassword   The password to log in with (optional)
     * @param xWorldName  (Optional) The name of the world as it appears in foundry if the world is
     *                    not already loaded. (optional)
     * @param requestBody (optional)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>OK</td>
     *                        <td>* X-Powered-By - <br>
     *                        * Access-Control-Allow-Origin - <br>
     *                        * Access-Control-Allow-Methods - <br>
     *                        * Access-Control-Allow-Headers - <br>
     *                        * Access-Control-Allow-Credentials - <br>
     *                        * Content-Type - <br>
     *                        * Content-Length - <br>
     *                        * ETag - <br>
     *                        * Date - <br>
     *                        * Connection - <br>
     *                        </td>
     *                        </tr>
     *                        </table>
     */
    public ApiResponse<Object> sessionHandshakePostWithHttpInfo(
            @jakarta.annotation.Nullable String xApiKey,
            @jakarta.annotation.Nullable String xFoundryUrl,
            @jakarta.annotation.Nullable String xUsername,
            @jakarta.annotation.Nullable String xPassword,
            @jakarta.annotation.Nullable String xWorldName,
            @jakarta.annotation.Nullable Map<String, Object> requestBody) throws ApiException {
        okhttp3.Call localVarCall = sessionHandshakePostValidateBeforeCall(xApiKey, xFoundryUrl,
                xUsername, xPassword, xWorldName, requestBody, null);
        Type localVarReturnType = new TypeToken<Object>() {
        }.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * /session-handshake (asynchronously) Creates a temporary, one-time-use, token that can be used
     * to create a headless Foundry session.
     * 
     * @param xApiKey     (optional)
     * @param xFoundryUrl The url to your foundry game (optional)
     * @param xUsername   The username to log in with (eg. \&quot;Gamemaster\&quot;) (optional)
     * @param xPassword   The password to log in with (optional)
     * @param xWorldName  (Optional) The name of the world as it appears in foundry if the world is
     *                    not already loaded. (optional)
     * @param requestBody (optional)
     * @param _callback   The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body
     *                      object
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>OK</td>
     *                        <td>* X-Powered-By - <br>
     *                        * Access-Control-Allow-Origin - <br>
     *                        * Access-Control-Allow-Methods - <br>
     *                        * Access-Control-Allow-Headers - <br>
     *                        * Access-Control-Allow-Credentials - <br>
     *                        * Content-Type - <br>
     *                        * Content-Length - <br>
     *                        * ETag - <br>
     *                        * Date - <br>
     *                        * Connection - <br>
     *                        </td>
     *                        </tr>
     *                        </table>
     */
    public okhttp3.Call sessionHandshakePostAsync(@jakarta.annotation.Nullable String xApiKey,
            @jakarta.annotation.Nullable String xFoundryUrl,
            @jakarta.annotation.Nullable String xUsername,
            @jakarta.annotation.Nullable String xPassword,
            @jakarta.annotation.Nullable String xWorldName,
            @jakarta.annotation.Nullable Map<String, Object> requestBody,
            final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = sessionHandshakePostValidateBeforeCall(xApiKey, xFoundryUrl,
                xUsername, xPassword, xWorldName, requestBody, _callback);
        Type localVarReturnType = new TypeToken<Object>() {
        }.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    /**
     * Build call for startSessionPost
     * 
     * @param xApiKey   (optional)
     * @param body      (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>OK</td>
     *                        <td>* X-Powered-By - <br>
     *                        * Access-Control-Allow-Origin - <br>
     *                        * Access-Control-Allow-Methods - <br>
     *                        * Access-Control-Allow-Headers - <br>
     *                        * Access-Control-Allow-Credentials - <br>
     *                        * Content-Type - <br>
     *                        * Content-Length - <br>
     *                        * ETag - <br>
     *                        * Date - <br>
     *                        * Connection - <br>
     *                        </td>
     *                        </tr>
     *                        </table>
     */
    public okhttp3.Call startSessionPostCall(@jakarta.annotation.Nullable String xApiKey,
            @jakarta.annotation.Nullable Object body, final ApiCallback _callback)
            throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {};

        // Determine Base Path to Use
        if (localCustomBaseUrl != null) {
            basePath = localCustomBaseUrl;
        } else if (localBasePaths.length > 0) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = body;

        // create path and map variables
        String localVarPath = "/start-session";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
                "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
                "application/json"
        };
        final String localVarContentType = localVarApiClient
                .selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xApiKey != null) {
            localVarHeaderParams.put("x-api-key", localVarApiClient.parameterToString(xApiKey));
        }

        String[] localVarAuthNames = new String[] {};
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams,
                localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams,
                localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call startSessionPostValidateBeforeCall(
            @jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable Object body,
            final ApiCallback _callback) throws ApiException {
        return startSessionPostCall(xApiKey, body, _callback);

    }

    /**
     * /start-session Starts a headless Foundry session. Must provide a handshake token and the
     * encrypted password.
     * 
     * @param xApiKey (optional)
     * @param body    (optional)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>OK</td>
     *                        <td>* X-Powered-By - <br>
     *                        * Access-Control-Allow-Origin - <br>
     *                        * Access-Control-Allow-Methods - <br>
     *                        * Access-Control-Allow-Headers - <br>
     *                        * Access-Control-Allow-Credentials - <br>
     *                        * Content-Type - <br>
     *                        * Content-Length - <br>
     *                        * ETag - <br>
     *                        * Date - <br>
     *                        * Connection - <br>
     *                        </td>
     *                        </tr>
     *                        </table>
     */
    public Object startSessionPost(@jakarta.annotation.Nullable String xApiKey,
            @jakarta.annotation.Nullable Object body) throws ApiException {
        ApiResponse<Object> localVarResp = startSessionPostWithHttpInfo(xApiKey, body);
        return localVarResp.getData();
    }

    /**
     * /start-session Starts a headless Foundry session. Must provide a handshake token and the
     * encrypted password.
     * 
     * @param xApiKey (optional)
     * @param body    (optional)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the
     *                      response body
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>OK</td>
     *                        <td>* X-Powered-By - <br>
     *                        * Access-Control-Allow-Origin - <br>
     *                        * Access-Control-Allow-Methods - <br>
     *                        * Access-Control-Allow-Headers - <br>
     *                        * Access-Control-Allow-Credentials - <br>
     *                        * Content-Type - <br>
     *                        * Content-Length - <br>
     *                        * ETag - <br>
     *                        * Date - <br>
     *                        * Connection - <br>
     *                        </td>
     *                        </tr>
     *                        </table>
     */
    public ApiResponse<Object> startSessionPostWithHttpInfo(
            @jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable Object body)
            throws ApiException {
        okhttp3.Call localVarCall = startSessionPostValidateBeforeCall(xApiKey, body, null);
        Type localVarReturnType = new TypeToken<Object>() {
        }.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * /start-session (asynchronously) Starts a headless Foundry session. Must provide a handshake
     * token and the encrypted password.
     * 
     * @param xApiKey   (optional)
     * @param body      (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body
     *                      object
     * @http.response.details
     *                        <table border="1">
     *                        <caption>Response Details</caption>
     *                        <tr>
     *                        <td>Status Code</td>
     *                        <td>Description</td>
     *                        <td>Response Headers</td>
     *                        </tr>
     *                        <tr>
     *                        <td>200</td>
     *                        <td>OK</td>
     *                        <td>* X-Powered-By - <br>
     *                        * Access-Control-Allow-Origin - <br>
     *                        * Access-Control-Allow-Methods - <br>
     *                        * Access-Control-Allow-Headers - <br>
     *                        * Access-Control-Allow-Credentials - <br>
     *                        * Content-Type - <br>
     *                        * Content-Length - <br>
     *                        * ETag - <br>
     *                        * Date - <br>
     *                        * Connection - <br>
     *                        </td>
     *                        </tr>
     *                        </table>
     */
    public okhttp3.Call startSessionPostAsync(@jakarta.annotation.Nullable String xApiKey,
            @jakarta.annotation.Nullable Object body, final ApiCallback<Object> _callback)
            throws ApiException {

        okhttp3.Call localVarCall = startSessionPostValidateBeforeCall(xApiKey, body, _callback);
        Type localVarReturnType = new TypeToken<Object>() {
        }.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
