/*
 * Foundry REST API Documentation
 * ### How to use Foundry REST API:  - Install the [Foundry VTT Module](https://github.com/ThreeHats/foundryvtt-rest-api) - Get an API key for the public relay server at [https://foundryvtt-rest-api-relay.fly.dev/](https://foundryvtt-rest-api-relay.fly.dev/) - Download [Postman](https://www.postman.com/downloads/) and the import the API Test Collection for an easy way to start testing endpoints. - Read this documentation for information about how to use each endpoint  ---  Foundry REST API provides various API endpoints for fetching and interacting with your foundry world data through a node.js server that act as a relay.  ## **Getting started guide**  To start using the Foundry REST API, you need to -  - Have your API key in the module settings. - Each request must have the your API key in the \"x-api-key\" header. - Endpoints other than /clients require a clientId parameter that matches a connected world.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.foundryvtt.bot.spirit.openapi.relay.client.api;

import com.foundryvtt.bot.spirit.openapi.relay.client.invoker.ApiCallback;
import com.foundryvtt.bot.spirit.openapi.relay.client.invoker.ApiClient;
import com.foundryvtt.bot.spirit.openapi.relay.client.invoker.ApiException;
import com.foundryvtt.bot.spirit.openapi.relay.client.invoker.ApiResponse;
import com.foundryvtt.bot.spirit.openapi.relay.client.invoker.Configuration;
import com.foundryvtt.bot.spirit.openapi.relay.client.invoker.Pair;
import com.foundryvtt.bot.spirit.openapi.relay.client.invoker.ProgressRequestBody;
import com.foundryvtt.bot.spirit.openapi.relay.client.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;



import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class DnD5eApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public DnD5eApi() {
        this(Configuration.getDefaultApiClient());
    }

    public DnD5eApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for dnd5eGetActorDetailsGet
     * @param xApiKey  (optional)
     * @param actorUuid  (optional)
     * @param details  (optional)
     * @param clientId  (optional)
     * @param actorUuid2  (optional)
     * @param details2  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call dnd5eGetActorDetailsGetCall(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String actorUuid, @jakarta.annotation.Nullable String details, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable String actorUuid2, @jakarta.annotation.Nullable String details2, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/dnd5e/get-actor-details";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (clientId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("clientId", clientId));
        }

        if (actorUuid2 != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("actorUuid", actorUuid2));
        }

        if (details2 != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("details", details2));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xApiKey != null) {
            localVarHeaderParams.put("x-api-key", localVarApiClient.parameterToString(xApiKey));
        }


        if (actorUuid != null) {
            localVarHeaderParams.put("actorUuid", localVarApiClient.parameterToString(actorUuid));
        }


        if (details != null) {
            localVarHeaderParams.put("details", localVarApiClient.parameterToString(details));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call dnd5eGetActorDetailsGetValidateBeforeCall(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String actorUuid, @jakarta.annotation.Nullable String details, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable String actorUuid2, @jakarta.annotation.Nullable String details2, final ApiCallback _callback) throws ApiException {
        return dnd5eGetActorDetailsGetCall(xApiKey, actorUuid, details, clientId, actorUuid2, details2, _callback);

    }

    /**
     * get-actor-details
     * 
     * @param xApiKey  (optional)
     * @param actorUuid  (optional)
     * @param details  (optional)
     * @param clientId  (optional)
     * @param actorUuid2  (optional)
     * @param details2  (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public void dnd5eGetActorDetailsGet(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String actorUuid, @jakarta.annotation.Nullable String details, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable String actorUuid2, @jakarta.annotation.Nullable String details2) throws ApiException {
        dnd5eGetActorDetailsGetWithHttpInfo(xApiKey, actorUuid, details, clientId, actorUuid2, details2);
    }

    /**
     * get-actor-details
     * 
     * @param xApiKey  (optional)
     * @param actorUuid  (optional)
     * @param details  (optional)
     * @param clientId  (optional)
     * @param actorUuid2  (optional)
     * @param details2  (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> dnd5eGetActorDetailsGetWithHttpInfo(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String actorUuid, @jakarta.annotation.Nullable String details, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable String actorUuid2, @jakarta.annotation.Nullable String details2) throws ApiException {
        okhttp3.Call localVarCall = dnd5eGetActorDetailsGetValidateBeforeCall(xApiKey, actorUuid, details, clientId, actorUuid2, details2, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * get-actor-details (asynchronously)
     * 
     * @param xApiKey  (optional)
     * @param actorUuid  (optional)
     * @param details  (optional)
     * @param clientId  (optional)
     * @param actorUuid2  (optional)
     * @param details2  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call dnd5eGetActorDetailsGetAsync(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String actorUuid, @jakarta.annotation.Nullable String details, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable String actorUuid2, @jakarta.annotation.Nullable String details2, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = dnd5eGetActorDetailsGetValidateBeforeCall(xApiKey, actorUuid, details, clientId, actorUuid2, details2, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for dnd5eModifyExperiencePost
     * @param xApiKey  (optional)
     * @param clientId  (optional)
     * @param actorUuid  (optional)
     * @param amount  (optional)
     * @param requestBody  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call dnd5eModifyExperiencePostCall(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable String actorUuid, @jakarta.annotation.Nullable Integer amount, @jakarta.annotation.Nullable Map<String, Object> requestBody, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = requestBody;

        // create path and map variables
        String localVarPath = "/dnd5e/modify-experience";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (clientId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("clientId", clientId));
        }

        if (actorUuid != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("actorUuid", actorUuid));
        }

        if (amount != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("amount", amount));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xApiKey != null) {
            localVarHeaderParams.put("x-api-key", localVarApiClient.parameterToString(xApiKey));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call dnd5eModifyExperiencePostValidateBeforeCall(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable String actorUuid, @jakarta.annotation.Nullable Integer amount, @jakarta.annotation.Nullable Map<String, Object> requestBody, final ApiCallback _callback) throws ApiException {
        return dnd5eModifyExperiencePostCall(xApiKey, clientId, actorUuid, amount, requestBody, _callback);

    }

    /**
     * modify-experience
     * 
     * @param xApiKey  (optional)
     * @param clientId  (optional)
     * @param actorUuid  (optional)
     * @param amount  (optional)
     * @param requestBody  (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public void dnd5eModifyExperiencePost(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable String actorUuid, @jakarta.annotation.Nullable Integer amount, @jakarta.annotation.Nullable Map<String, Object> requestBody) throws ApiException {
        dnd5eModifyExperiencePostWithHttpInfo(xApiKey, clientId, actorUuid, amount, requestBody);
    }

    /**
     * modify-experience
     * 
     * @param xApiKey  (optional)
     * @param clientId  (optional)
     * @param actorUuid  (optional)
     * @param amount  (optional)
     * @param requestBody  (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> dnd5eModifyExperiencePostWithHttpInfo(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable String actorUuid, @jakarta.annotation.Nullable Integer amount, @jakarta.annotation.Nullable Map<String, Object> requestBody) throws ApiException {
        okhttp3.Call localVarCall = dnd5eModifyExperiencePostValidateBeforeCall(xApiKey, clientId, actorUuid, amount, requestBody, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * modify-experience (asynchronously)
     * 
     * @param xApiKey  (optional)
     * @param clientId  (optional)
     * @param actorUuid  (optional)
     * @param amount  (optional)
     * @param requestBody  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call dnd5eModifyExperiencePostAsync(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable String actorUuid, @jakarta.annotation.Nullable Integer amount, @jakarta.annotation.Nullable Map<String, Object> requestBody, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = dnd5eModifyExperiencePostValidateBeforeCall(xApiKey, clientId, actorUuid, amount, requestBody, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for dnd5eModifyItemChargesPost
     * @param xApiKey  (optional)
     * @param clientId  (optional)
     * @param actorUuid  (optional)
     * @param itemName  (optional)
     * @param amount  (optional)
     * @param requestBody  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call dnd5eModifyItemChargesPostCall(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable String actorUuid, @jakarta.annotation.Nullable String itemName, @jakarta.annotation.Nullable String amount, @jakarta.annotation.Nullable Map<String, Object> requestBody, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = requestBody;

        // create path and map variables
        String localVarPath = "/dnd5e/modify-item-charges";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (clientId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("clientId", clientId));
        }

        if (actorUuid != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("actorUuid", actorUuid));
        }

        if (itemName != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("itemName", itemName));
        }

        if (amount != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("amount", amount));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xApiKey != null) {
            localVarHeaderParams.put("x-api-key", localVarApiClient.parameterToString(xApiKey));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call dnd5eModifyItemChargesPostValidateBeforeCall(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable String actorUuid, @jakarta.annotation.Nullable String itemName, @jakarta.annotation.Nullable String amount, @jakarta.annotation.Nullable Map<String, Object> requestBody, final ApiCallback _callback) throws ApiException {
        return dnd5eModifyItemChargesPostCall(xApiKey, clientId, actorUuid, itemName, amount, requestBody, _callback);

    }

    /**
     * modify-item-charges
     * 
     * @param xApiKey  (optional)
     * @param clientId  (optional)
     * @param actorUuid  (optional)
     * @param itemName  (optional)
     * @param amount  (optional)
     * @param requestBody  (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public void dnd5eModifyItemChargesPost(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable String actorUuid, @jakarta.annotation.Nullable String itemName, @jakarta.annotation.Nullable String amount, @jakarta.annotation.Nullable Map<String, Object> requestBody) throws ApiException {
        dnd5eModifyItemChargesPostWithHttpInfo(xApiKey, clientId, actorUuid, itemName, amount, requestBody);
    }

    /**
     * modify-item-charges
     * 
     * @param xApiKey  (optional)
     * @param clientId  (optional)
     * @param actorUuid  (optional)
     * @param itemName  (optional)
     * @param amount  (optional)
     * @param requestBody  (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> dnd5eModifyItemChargesPostWithHttpInfo(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable String actorUuid, @jakarta.annotation.Nullable String itemName, @jakarta.annotation.Nullable String amount, @jakarta.annotation.Nullable Map<String, Object> requestBody) throws ApiException {
        okhttp3.Call localVarCall = dnd5eModifyItemChargesPostValidateBeforeCall(xApiKey, clientId, actorUuid, itemName, amount, requestBody, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * modify-item-charges (asynchronously)
     * 
     * @param xApiKey  (optional)
     * @param clientId  (optional)
     * @param actorUuid  (optional)
     * @param itemName  (optional)
     * @param amount  (optional)
     * @param requestBody  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call dnd5eModifyItemChargesPostAsync(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable String actorUuid, @jakarta.annotation.Nullable String itemName, @jakarta.annotation.Nullable String amount, @jakarta.annotation.Nullable Map<String, Object> requestBody, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = dnd5eModifyItemChargesPostValidateBeforeCall(xApiKey, clientId, actorUuid, itemName, amount, requestBody, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for dnd5eUseAbilityPost
     * @param xApiKey  (optional)
     * @param actorUuid  (optional)
     * @param details  (optional)
     * @param clientId  (optional)
     * @param actorUuid2  (optional)
     * @param abilityName  (optional)
     * @param requestBody  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call dnd5eUseAbilityPostCall(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String actorUuid, @jakarta.annotation.Nullable String details, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable String actorUuid2, @jakarta.annotation.Nullable String abilityName, @jakarta.annotation.Nullable Map<String, Object> requestBody, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = requestBody;

        // create path and map variables
        String localVarPath = "/dnd5e/use-ability";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (clientId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("clientId", clientId));
        }

        if (actorUuid2 != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("actorUuid", actorUuid2));
        }

        if (abilityName != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("abilityName", abilityName));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xApiKey != null) {
            localVarHeaderParams.put("x-api-key", localVarApiClient.parameterToString(xApiKey));
        }


        if (actorUuid != null) {
            localVarHeaderParams.put("actorUuid", localVarApiClient.parameterToString(actorUuid));
        }


        if (details != null) {
            localVarHeaderParams.put("details", localVarApiClient.parameterToString(details));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call dnd5eUseAbilityPostValidateBeforeCall(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String actorUuid, @jakarta.annotation.Nullable String details, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable String actorUuid2, @jakarta.annotation.Nullable String abilityName, @jakarta.annotation.Nullable Map<String, Object> requestBody, final ApiCallback _callback) throws ApiException {
        return dnd5eUseAbilityPostCall(xApiKey, actorUuid, details, clientId, actorUuid2, abilityName, requestBody, _callback);

    }

    /**
     * use-item
     * 
     * @param xApiKey  (optional)
     * @param actorUuid  (optional)
     * @param details  (optional)
     * @param clientId  (optional)
     * @param actorUuid2  (optional)
     * @param abilityName  (optional)
     * @param requestBody  (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public void dnd5eUseAbilityPost(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String actorUuid, @jakarta.annotation.Nullable String details, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable String actorUuid2, @jakarta.annotation.Nullable String abilityName, @jakarta.annotation.Nullable Map<String, Object> requestBody) throws ApiException {
        dnd5eUseAbilityPostWithHttpInfo(xApiKey, actorUuid, details, clientId, actorUuid2, abilityName, requestBody);
    }

    /**
     * use-item
     * 
     * @param xApiKey  (optional)
     * @param actorUuid  (optional)
     * @param details  (optional)
     * @param clientId  (optional)
     * @param actorUuid2  (optional)
     * @param abilityName  (optional)
     * @param requestBody  (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Void> dnd5eUseAbilityPostWithHttpInfo(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String actorUuid, @jakarta.annotation.Nullable String details, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable String actorUuid2, @jakarta.annotation.Nullable String abilityName, @jakarta.annotation.Nullable Map<String, Object> requestBody) throws ApiException {
        okhttp3.Call localVarCall = dnd5eUseAbilityPostValidateBeforeCall(xApiKey, actorUuid, details, clientId, actorUuid2, abilityName, requestBody, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * use-item (asynchronously)
     * 
     * @param xApiKey  (optional)
     * @param actorUuid  (optional)
     * @param details  (optional)
     * @param clientId  (optional)
     * @param actorUuid2  (optional)
     * @param abilityName  (optional)
     * @param requestBody  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Successful response </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call dnd5eUseAbilityPostAsync(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String actorUuid, @jakarta.annotation.Nullable String details, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable String actorUuid2, @jakarta.annotation.Nullable String abilityName, @jakarta.annotation.Nullable Map<String, Object> requestBody, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = dnd5eUseAbilityPostValidateBeforeCall(xApiKey, actorUuid, details, clientId, actorUuid2, abilityName, requestBody, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
