/*
 * Foundry REST API Documentation
 * ### How to use Foundry REST API:  - Install the [Foundry VTT Module](https://github.com/ThreeHats/foundryvtt-rest-api) - Get an API key for the public relay server at [https://foundryvtt-rest-api-relay.fly.dev/](https://foundryvtt-rest-api-relay.fly.dev/) - Download [Postman](https://www.postman.com/downloads/) and the import the API Test Collection for an easy way to start testing endpoints. - Read this documentation for information about how to use each endpoint  ---  Foundry REST API provides various API endpoints for fetching and interacting with your foundry world data through a node.js server that act as a relay.  ## **Getting started guide**  To start using the Foundry REST API, you need to -  - Have your API key in the module settings. - Each request must have the your API key in the \"x-api-key\" header. - Endpoints other than /clients require a clientId parameter that matches a connected world.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.foundryvtt.bot.spirit.openapi.relay.v13.system.core.model;

import java.util.Objects;
import com.foundryvtt.bot.spirit.openapi.relay.v13.system.core.model.Actor;
import com.foundryvtt.bot.spirit.openapi.relay.v13.system.core.model.Item;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import com.foundryvtt.bot.spirit.openapi.relay.v13.system.core.invoker.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class CreatePostRequest extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(CreatePostRequest.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!CreatePostRequest.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'CreatePostRequest' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<Actor> adapterActor = gson.getDelegateAdapter(this, TypeToken.get(Actor.class));
            final TypeAdapter<Item> adapterItem = gson.getDelegateAdapter(this, TypeToken.get(Item.class));

            return (TypeAdapter<T>) new TypeAdapter<CreatePostRequest>() {
                @Override
                public void write(JsonWriter out, CreatePostRequest value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `Actor`
                    if (value.getActualInstance() instanceof Actor) {
                        JsonElement element = adapterActor.toJsonTree((Actor)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `Item`
                    if (value.getActualInstance() instanceof Item) {
                        JsonElement element = adapterItem.toJsonTree((Item)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: Actor, Item");
                }

                @Override
                public CreatePostRequest read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize Actor
                    try {
                        // validate the JSON object to see if any exception is thrown
                        Actor.validateJsonElement(jsonElement);
                        actualAdapter = adapterActor;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'Actor'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for Actor failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'Actor'", e);
                    }
                    // deserialize Item
                    try {
                        // validate the JSON object to see if any exception is thrown
                        Item.validateJsonElement(jsonElement);
                        actualAdapter = adapterItem;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'Item'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for Item failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'Item'", e);
                    }

                    if (match == 1) {
                        CreatePostRequest ret = new CreatePostRequest();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format(java.util.Locale.ROOT, "Failed deserialization for CreatePostRequest: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public CreatePostRequest() {
        super("oneOf", Boolean.FALSE);
    }

    public CreatePostRequest(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("Actor", Actor.class);
        schemas.put("Item", Item.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return CreatePostRequest.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * Actor, Item
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof Actor) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof Item) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be Actor, Item");
    }

    /**
     * Get the actual instance, which can be the following:
     * Actor, Item
     *
     * @return The actual instance (Actor, Item)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `Actor`. If the actual instance is not `Actor`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Actor`
     * @throws ClassCastException if the instance is not `Actor`
     */
    public Actor getActor() throws ClassCastException {
        return (Actor)super.getActualInstance();
    }

    /**
     * Get the actual instance of `Item`. If the actual instance is not `Item`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `Item`
     * @throws ClassCastException if the instance is not `Item`
     */
    public Item getItem() throws ClassCastException {
        return (Item)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to CreatePostRequest
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with Actor
        try {
            Actor.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for Actor failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with Item
        try {
            Item.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format(java.util.Locale.ROOT, "Deserialization for Item failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format(java.util.Locale.ROOT, "The JSON string is invalid for CreatePostRequest with oneOf schemas: Actor, Item. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of CreatePostRequest given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of CreatePostRequest
     * @throws IOException if the JSON string is invalid with respect to CreatePostRequest
     */
    public static CreatePostRequest fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, CreatePostRequest.class);
    }

    /**
     * Convert an instance of CreatePostRequest to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

