/*
 * Foundry REST API Documentation
 * ### How to use Foundry REST API:  - Install the [Foundry VTT Module](https://github.com/ThreeHats/foundryvtt-rest-api) - Get an API key for the public relay server at [https://foundryvtt-rest-api-relay.fly.dev/](https://foundryvtt-rest-api-relay.fly.dev/) - Download [Postman](https://www.postman.com/downloads/) and the import the API Test Collection for an easy way to start testing endpoints. - Read this documentation for information about how to use each endpoint  ---  Foundry REST API provides various API endpoints for fetching and interacting with your foundry world data through a node.js server that act as a relay.  ## **Getting started guide**  To start using the Foundry REST API, you need to -  - Have your API key in the module settings. - Each request must have the your API key in the \"x-api-key\" header. - Endpoints other than /clients require a clientId parameter that matches a connected world.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.foundryvtt.bot.spirit.openapi.relay.system.core.api;

import com.foundryvtt.bot.spirit.openapi.relay.system.core.invoker.ApiCallback;
import com.foundryvtt.bot.spirit.openapi.relay.system.core.invoker.ApiClient;
import com.foundryvtt.bot.spirit.openapi.relay.system.core.invoker.ApiException;
import com.foundryvtt.bot.spirit.openapi.relay.system.core.invoker.ApiResponse;
import com.foundryvtt.bot.spirit.openapi.relay.system.core.invoker.Configuration;
import com.foundryvtt.bot.spirit.openapi.relay.system.core.invoker.Pair;
import com.foundryvtt.bot.spirit.openapi.relay.system.core.invoker.ProgressRequestBody;
import com.foundryvtt.bot.spirit.openapi.relay.system.core.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import java.math.BigDecimal;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SheetApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public SheetApi() {
        this(Configuration.getDefaultApiClient());
    }

    public SheetApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for sheetGet
     * @param xApiKey  (optional)
     * @param clientId Auth token to connect to specific Foundry world (optional)
     * @param selected (Optional) Tab to open if available (optional)
     * @param actor (Optional) Return dark mode HTML. Default &#x3D; false (optional)
     * @param scale  (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  * x-powered-by -  <br>  * access-control-allow-origin -  <br>  * access-control-allow-methods -  <br>  * access-control-allow-headers -  <br>  * access-control-allow-credentials -  <br>  * content-type -  <br>  * content-encoding -  <br>  * etag -  <br>  * date -  <br>  * connection -  <br>  * transfer-encoding -  <br>  * server -  <br>  * via -  <br>  * fly-request-id -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call sheetGetCall(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable Boolean selected, @jakarta.annotation.Nullable Boolean actor, @jakarta.annotation.Nullable BigDecimal scale, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/sheet";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (clientId != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("clientId", clientId));
        }

        if (selected != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("selected", selected));
        }

        if (actor != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("actor", actor));
        }

        if (scale != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("scale", scale));
        }

        final String[] localVarAccepts = {
            "text/plain"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xApiKey != null) {
            localVarHeaderParams.put("x-api-key", localVarApiClient.parameterToString(xApiKey));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call sheetGetValidateBeforeCall(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable Boolean selected, @jakarta.annotation.Nullable Boolean actor, @jakarta.annotation.Nullable BigDecimal scale, final ApiCallback _callback) throws ApiException {
        return sheetGetCall(xApiKey, clientId, selected, actor, scale, _callback);

    }

    /**
     * /sheet
     * ## Returns raw HTML (or a string in a JSON response) for an entity  If returning HTML there are options for scale, tab to open (if available), and darkMode.  If returning JSON the HTML is untouched.
     * @param xApiKey  (optional)
     * @param clientId Auth token to connect to specific Foundry world (optional)
     * @param selected (Optional) Tab to open if available (optional)
     * @param actor (Optional) Return dark mode HTML. Default &#x3D; false (optional)
     * @param scale  (optional)
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  * x-powered-by -  <br>  * access-control-allow-origin -  <br>  * access-control-allow-methods -  <br>  * access-control-allow-headers -  <br>  * access-control-allow-credentials -  <br>  * content-type -  <br>  * content-encoding -  <br>  * etag -  <br>  * date -  <br>  * connection -  <br>  * transfer-encoding -  <br>  * server -  <br>  * via -  <br>  * fly-request-id -  <br>  </td></tr>
     </table>
     */
    public String sheetGet(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable Boolean selected, @jakarta.annotation.Nullable Boolean actor, @jakarta.annotation.Nullable BigDecimal scale) throws ApiException {
        ApiResponse<String> localVarResp = sheetGetWithHttpInfo(xApiKey, clientId, selected, actor, scale);
        return localVarResp.getData();
    }

    /**
     * /sheet
     * ## Returns raw HTML (or a string in a JSON response) for an entity  If returning HTML there are options for scale, tab to open (if available), and darkMode.  If returning JSON the HTML is untouched.
     * @param xApiKey  (optional)
     * @param clientId Auth token to connect to specific Foundry world (optional)
     * @param selected (Optional) Tab to open if available (optional)
     * @param actor (Optional) Return dark mode HTML. Default &#x3D; false (optional)
     * @param scale  (optional)
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  * x-powered-by -  <br>  * access-control-allow-origin -  <br>  * access-control-allow-methods -  <br>  * access-control-allow-headers -  <br>  * access-control-allow-credentials -  <br>  * content-type -  <br>  * content-encoding -  <br>  * etag -  <br>  * date -  <br>  * connection -  <br>  * transfer-encoding -  <br>  * server -  <br>  * via -  <br>  * fly-request-id -  <br>  </td></tr>
     </table>
     */
    public ApiResponse<String> sheetGetWithHttpInfo(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable Boolean selected, @jakarta.annotation.Nullable Boolean actor, @jakarta.annotation.Nullable BigDecimal scale) throws ApiException {
        okhttp3.Call localVarCall = sheetGetValidateBeforeCall(xApiKey, clientId, selected, actor, scale, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * /sheet (asynchronously)
     * ## Returns raw HTML (or a string in a JSON response) for an entity  If returning HTML there are options for scale, tab to open (if available), and darkMode.  If returning JSON the HTML is untouched.
     * @param xApiKey  (optional)
     * @param clientId Auth token to connect to specific Foundry world (optional)
     * @param selected (Optional) Tab to open if available (optional)
     * @param actor (Optional) Return dark mode HTML. Default &#x3D; false (optional)
     * @param scale  (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  * x-powered-by -  <br>  * access-control-allow-origin -  <br>  * access-control-allow-methods -  <br>  * access-control-allow-headers -  <br>  * access-control-allow-credentials -  <br>  * content-type -  <br>  * content-encoding -  <br>  * etag -  <br>  * date -  <br>  * connection -  <br>  * transfer-encoding -  <br>  * server -  <br>  * via -  <br>  * fly-request-id -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call sheetGetAsync(@jakarta.annotation.Nullable String xApiKey, @jakarta.annotation.Nullable String clientId, @jakarta.annotation.Nullable Boolean selected, @jakarta.annotation.Nullable Boolean actor, @jakarta.annotation.Nullable BigDecimal scale, final ApiCallback<String> _callback) throws ApiException {

        okhttp3.Call localVarCall = sheetGetValidateBeforeCall(xApiKey, clientId, selected, actor, scale, _callback);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
